### ISSUE TITLE
it always shows "Rendering pdf.. "

### ISSUE THREAD

**Issue by yashfale** [leonibr/invoice_samurai#1]
Hi , 

i have ran the project but pdf is not rendering it always shows "Rendering pdf.. "

Tool : Visual studio 22  

-Thanks

**Comment by leonibr** [comment]
Hi, try with chrome, some browsers do not allow iframe pdf by default

**Comment by leonibr** [comment]
![Screenshot (69)](https://user-images.githubusercontent.com/7917333/131387252-793f3cc8-c460-4eeb-95f6-a9385738f1af.png)
It is working fine here

**Comment by yashfale** [comment]
I have tried this but only i can able to run with internet explorer but still not working that pdf.

Checked with Following :  Chrome , Edge (updated version) 
``
i am getting the following error when i use chrome or edge .

![Error](https://user-images.githubusercontent.com/7036028/131468143-cc43d7ac-d85e-415e-a308-e3e139c5edfc.JPG)
![more error](https://user-images.githubusercontent.com/7036028/131468146-7f945373-a942-4995-b45e-eb39f965f015.JPG)

not sure why this happening , eve i am using latest vs2022 and also vs2019

**Comment by yashfale** [comment]
Issue has been resolved , i have updated visual studio and ran the server app , its working .

Note : not working Client App for that pdf view 

- Thanks
